// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDToi9EqVpSCxn8ZvfUC2CqgVYFYLm99p0',
    appId: '1:389626556657:web:e54c862261e25d3d577950',
    messagingSenderId: '389626556657',
    projectId: 'rpg-handler',
    authDomain: 'rpg-handler.firebaseapp.com',
    databaseURL: 'https://rpg-handler-default-rtdb.firebaseio.com',
    storageBucket: 'rpg-handler.appspot.com',
    measurementId: 'G-NW75YGHG8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2pPf-Lgbi_q7JKrtsf9pUIUfbjIk308Y',
    appId: '1:389626556657:android:aa8afd5edd6a65c6577950',
    messagingSenderId: '389626556657',
    projectId: 'rpg-handler',
    databaseURL: 'https://rpg-handler-default-rtdb.firebaseio.com',
    storageBucket: 'rpg-handler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLcXI-w_uLRyHcY6VQWmoXXQ7HRg9yzMU',
    appId: '1:389626556657:ios:c617d0e19eebe229577950',
    messagingSenderId: '389626556657',
    projectId: 'rpg-handler',
    databaseURL: 'https://rpg-handler-default-rtdb.firebaseio.com',
    storageBucket: 'rpg-handler.appspot.com',
    iosClientId: '389626556657-nf4c8kbmg4a45k0po07hanco004m96k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.apprpg',
  );
}
